CREATE USER 'gymadmin'@'%' IDENTIFIED BY 'Q111111q';
GRANT ALL ON GYM_JOURNAL_DB.* TO 'gymadmin'@'%';
GRANT ALL ON GYM_JOURNAL_DB TO 'gymadmin'@'%';
GRANT CREATE ON GYM_JOURNAL_DB TO 'gymadmin'@'%';
FLUSH PRIVILEGES;
