-- Таблица транзакционных логов
DROP TABLE IF EXISTS GYM_JOURNAL_DB.TRANSACTION_LOG;

CREATE TABLE GYM_JOURNAL_DB.TRANSACTION_LOG (
	TRANSACTION_ID VARCHAR(128) NOT NULL PRIMARY KEY,
	START_DT DATETIME NOT NULL,
	END_DT DATETIME NULL
);

-- Категории упражнений
DROP TABLE IF EXISTS GYM_JOURNAL_DB.EXERCISE_CATEGORY; 

CREATE TABLE GYM_JOURNAL_DB.EXERCISE_CATEGORY (
	CATEGORY_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(256) NOT NULL,
	DESCRIPTION VARCHAR(2048) NULL
);

-- Справочник упражнений
DROP TABLE IF EXISTS GYM_JOURNAL_DB.EXERCISE;

CREATE TABLE GYM_JOURNAL_DB.EXERCISE (
	EXERCISE_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CATEGORY_ID BIGINT NOT NULL,
	NAME VARCHAR(256) NOT NULL,
	DESCRIPTION VARCHAR(2048) NULL
);