-- Категории упражнений
DELETE FROM GYM_JOURNAL_DB.EXERCISE_CATEGORY;

INSERT INTO GYM_JOURNAL_DB.EXERCISE_CATEGORY (NAME, DESCRIPTION) VALUES ('Мышцы спины', 'Мышцы спины');
INSERT INTO GYM_JOURNAL_DB.EXERCISE_CATEGORY (NAME, DESCRIPTION) VALUES ('Мышцы пресса', 'Мышцы пресса');
INSERT INTO GYM_JOURNAL_DB.EXERCISE_CATEGORY (NAME, DESCRIPTION) VALUES ('Бицепсы', 'Бицепсы');
INSERT INTO GYM_JOURNAL_DB.EXERCISE_CATEGORY (NAME, DESCRIPTION) VALUES ('Голени', 'Голени');
INSERT INTO GYM_JOURNAL_DB.EXERCISE_CATEGORY (NAME, DESCRIPTION) VALUES ('Грудная клетка', 'Грудная клетка');
INSERT INTO GYM_JOURNAL_DB.EXERCISE_CATEGORY (NAME, DESCRIPTION) VALUES ('Предплечья', 'Предплечья');
INSERT INTO GYM_JOURNAL_DB.EXERCISE_CATEGORY (NAME, DESCRIPTION) VALUES ('Ноги', 'Ноги');
INSERT INTO GYM_JOURNAL_DB.EXERCISE_CATEGORY (NAME, DESCRIPTION) VALUES ('Плечи', 'Плечи');
INSERT INTO GYM_JOURNAL_DB.EXERCISE_CATEGORY (NAME, DESCRIPTION) VALUES ('Трицепсы', 'Трицепсы');