package org.talend.designer.codegen.translators.databases.teradata;

import org.talend.core.model.process.INode;
import org.talend.core.model.process.ElementParameterParser;
import org.talend.core.model.metadata.IMetadataTable;
import org.talend.core.model.metadata.IMetadataColumn;
import org.talend.designer.codegen.config.CodeGeneratorArgument;
import java.util.List;
import java.lang.StringBuilder;

public class TTeradataTPTExecMainJava
{
  protected static String nl;
  public static synchronized TTeradataTPTExecMainJava create(String lineSeparator)
  {
    nl = lineSeparator;
    TTeradataTPTExecMainJava result = new TTeradataTPTExecMainJava();
    nl = null;
    return result;
  }

  public final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "String tableFullName_";
  protected final String TEXT_2 = " = ";
  protected final String TEXT_3 = " + \".\" + ";
  protected final String TEXT_4 = ";" + NL + "java.io.File file_";
  protected final String TEXT_5 = " = new java.io.File(";
  protected final String TEXT_6 = "+";
  protected final String TEXT_7 = "+ ";
  protected final String TEXT_8 = "\".script\"";
  protected final String TEXT_9 = "\".scr\"";
  protected final String TEXT_10 = ");" + NL;
  protected final String TEXT_11 = NL + NL + "try{" + NL + "java.io.FileWriter fw_";
  protected final String TEXT_12 = " = new java.io.FileWriter(file_";
  protected final String TEXT_13 = ");" + NL + "fw_";
  protected final String TEXT_14 = ".write(\"/* 1 */  ";
  protected final String TEXT_15 = "\");" + NL + "fw_";
  protected final String TEXT_16 = ".write(\"/* 2 */  ";
  protected final String TEXT_17 = "\");" + NL + "fw_";
  protected final String TEXT_18 = ".write(\"/* 3 */  DEFINE JOB \" + ";
  protected final String TEXT_19 = " +\"";
  protected final String TEXT_20 = "\");" + NL + "fw_";
  protected final String TEXT_21 = ".write(\"/* 4 */  (\"+\"";
  protected final String TEXT_22 = "\");" + NL + "fw_";
  protected final String TEXT_23 = ".write(\"/* 5 */  \tDEFINE OPERATOR \" + ";
  protected final String TEXT_24 = " + \"";
  protected final String TEXT_25 = "\");" + NL + "fw_";
  protected final String TEXT_26 = ".write(\"/* 6 */  \tTYPE LOAD";
  protected final String TEXT_27 = "\");" + NL + "fw_";
  protected final String TEXT_28 = ".write(\"/* 7 */  \tSCHEMA *";
  protected final String TEXT_29 = "\");" + NL + "fw_";
  protected final String TEXT_30 = ".write(\"/* 8 */  \tATTRIBUTES";
  protected final String TEXT_31 = "\");" + NL + "fw_";
  protected final String TEXT_32 = ".write(\"/* 9 */  \t(";
  protected final String TEXT_33 = "\");" + NL + "fw_";
  protected final String TEXT_34 = ".write(\"/* 10 */  \t\tVARCHAR UserName, ";
  protected final String TEXT_35 = "\");" + NL + "fw_";
  protected final String TEXT_36 = ".write(\"/* 11 */  \t\tVARCHAR UserPassword, ";
  protected final String TEXT_37 = "\");" + NL + "fw_";
  protected final String TEXT_38 = ".write(\"/* 12 */  \t\tVARCHAR LogTable, ";
  protected final String TEXT_39 = "\");" + NL + "fw_";
  protected final String TEXT_40 = ".write(\"/* 13 */  \t\tVARCHAR TargetTable, ";
  protected final String TEXT_41 = "\");" + NL + "fw_";
  protected final String TEXT_42 = ".write(\"/* 14 */  \t\tINTEGER BufferSize, ";
  protected final String TEXT_43 = "\");" + NL + "fw_";
  protected final String TEXT_44 = ".write(\"/* 15 */  \t\tINTEGER ErrorLimit, ";
  protected final String TEXT_45 = "\");" + NL + "fw_";
  protected final String TEXT_46 = ".write(\"/* 16 */  \t\tINTEGER MaxSessions, ";
  protected final String TEXT_47 = "\");" + NL + "fw_";
  protected final String TEXT_48 = ".write(\"/* 17 */  \t\tINTEGER MinSessions, ";
  protected final String TEXT_49 = "\");" + NL + "fw_";
  protected final String TEXT_50 = ".write(\"/* 18 */  \t\tINTEGER TenacityHours, ";
  protected final String TEXT_51 = "\");" + NL + "fw_";
  protected final String TEXT_52 = ".write(\"/* 19 */  \t\tINTEGER TenacitySleep, ";
  protected final String TEXT_53 = "\");" + NL + "fw_";
  protected final String TEXT_54 = ".write(\"/* 20 */  \t\tVARCHAR AccountID, ";
  protected final String TEXT_55 = "\");" + NL + "fw_";
  protected final String TEXT_56 = ".write(\"/* 21 */  \t\tVARCHAR DateForm, ";
  protected final String TEXT_57 = "\");" + NL + "fw_";
  protected final String TEXT_58 = ".write(\"/* 22 */  \t\tVARCHAR ErrorTable1, ";
  protected final String TEXT_59 = "\");" + NL + "fw_";
  protected final String TEXT_60 = ".write(\"/* 23 */  \t\tVARCHAR ErrorTable2, ";
  protected final String TEXT_61 = "\");" + NL + "fw_";
  protected final String TEXT_62 = ".write(\"/* 24 */  \t\tVARCHAR NotifyExit, ";
  protected final String TEXT_63 = "\");" + NL + "fw_";
  protected final String TEXT_64 = ".write(\"/* 25 */  \t\tVARCHAR NotifyExitIsDLL, ";
  protected final String TEXT_65 = "\");" + NL + "fw_";
  protected final String TEXT_66 = ".write(\"/* 26 */  \t\tVARCHAR NotifyLevel, ";
  protected final String TEXT_67 = "\");" + NL + "fw_";
  protected final String TEXT_68 = ".write(\"/* 27 */  \t\tVARCHAR NotifyMethod, ";
  protected final String TEXT_69 = "\");" + NL + "fw_";
  protected final String TEXT_70 = ".write(\"/* 28 */  \t\tVARCHAR NotifyString, ";
  protected final String TEXT_71 = "\");" + NL + "fw_";
  protected final String TEXT_72 = ".write(\"/* 29 */  \t\tVARCHAR PauseAcq, ";
  protected final String TEXT_73 = "\");" + NL + "fw_";
  protected final String TEXT_74 = ".write(\"/* 30 */  \t\tVARCHAR PrivateLogName,";
  protected final String TEXT_75 = "\"); " + NL + "fw_";
  protected final String TEXT_76 = ".write(\"/* 31 */  \t\tVARCHAR TdpId, ";
  protected final String TEXT_77 = "\");" + NL + "fw_";
  protected final String TEXT_78 = ".write(\"/* 32 */  \t\tVARCHAR TraceLevel, ";
  protected final String TEXT_79 = "\");" + NL + "fw_";
  protected final String TEXT_80 = ".write(\"/* 33 */  \t\tVARCHAR WorkingDatabase";
  protected final String TEXT_81 = "\");" + NL + "fw_";
  protected final String TEXT_82 = ".write(\"/* 34 */  \t);";
  protected final String TEXT_83 = "\");" + NL + "fw_";
  protected final String TEXT_84 = ".write(\"/* 35 */  ";
  protected final String TEXT_85 = "\");" + NL + "fw_";
  protected final String TEXT_86 = ".write(\"/* 36 */  \tDEFINE SCHEMA \" + ";
  protected final String TEXT_87 = " + \"";
  protected final String TEXT_88 = "\");" + NL + "fw_";
  protected final String TEXT_89 = ".write(\"/* 37 */  \t(";
  protected final String TEXT_90 = "\");" + NL;
  protected final String TEXT_91 = NL + "\t\tfw_";
  protected final String TEXT_92 = ".write(\"               ";
  protected final String TEXT_93 = "\"+\" VARCHAR(";
  protected final String TEXT_94 = "),";
  protected final String TEXT_95 = "\");" + NL + "\t";
  protected final String TEXT_96 = NL + "\t\t\tfw_";
  protected final String TEXT_97 = ".write(\"               ";
  protected final String TEXT_98 = "\"+\" VARCHAR(";
  protected final String TEXT_99 = ")";
  protected final String TEXT_100 = "\");" + NL + "\t";
  protected final String TEXT_101 = NL + NL + "fw_";
  protected final String TEXT_102 = ".write(\"/* 45 */  \t);";
  protected final String TEXT_103 = "\");" + NL + "fw_";
  protected final String TEXT_104 = ".write(\"/* 46 */  ";
  protected final String TEXT_105 = "\");" + NL + "fw_";
  protected final String TEXT_106 = ".write(\"/* 47 */  \tDEFINE OPERATOR \" + ";
  protected final String TEXT_107 = " + \"";
  protected final String TEXT_108 = "\");" + NL + "fw_";
  protected final String TEXT_109 = ".write(\"/* 48 */  \tTYPE DATACONNECTOR PRODUCER";
  protected final String TEXT_110 = "\");" + NL + "fw_";
  protected final String TEXT_111 = ".write(\"/* 49 */  \tSCHEMA \" + ";
  protected final String TEXT_112 = " + \"";
  protected final String TEXT_113 = "\");" + NL + "fw_";
  protected final String TEXT_114 = ".write(\"/* 50 */  \tATTRIBUTES";
  protected final String TEXT_115 = "\");" + NL + "fw_";
  protected final String TEXT_116 = ".write(\"/* 51 */  \t(";
  protected final String TEXT_117 = "\");" + NL + "fw_";
  protected final String TEXT_118 = ".write(\"/* 52 */  \t\tVARCHAR FileName, ";
  protected final String TEXT_119 = "\");" + NL + "fw_";
  protected final String TEXT_120 = ".write(\"/* 53 */  \t\tVARCHAR Format, ";
  protected final String TEXT_121 = "\");" + NL + "fw_";
  protected final String TEXT_122 = ".write(\"/* 54 */  \t\tVARCHAR OpenMode, ";
  protected final String TEXT_123 = "\");" + NL + "fw_";
  protected final String TEXT_124 = ".write(\"/* 55 */  \t\tINTEGER BlockSize, ";
  protected final String TEXT_125 = "\");" + NL + "fw_";
  protected final String TEXT_126 = ".write(\"/* 56 */  \t\tINTEGER BufferSize, ";
  protected final String TEXT_127 = "\");" + NL + "fw_";
  protected final String TEXT_128 = ".write(\"/* 57 */  \t\tINTEGER RetentionPeriod, ";
  protected final String TEXT_129 = "\");" + NL + "fw_";
  protected final String TEXT_130 = ".write(\"/* 58 */  \t\tINTEGER RowsPerInstance, ";
  protected final String TEXT_131 = "\");" + NL + "fw_";
  protected final String TEXT_132 = ".write(\"/* 59 */  \t\tINTEGER SecondarySpace, ";
  protected final String TEXT_133 = "\");" + NL + "fw_";
  protected final String TEXT_134 = ".write(\"/* 60 */  \t\tINTEGER UnitCount, ";
  protected final String TEXT_135 = "\");" + NL + "fw_";
  protected final String TEXT_136 = ".write(\"/* 61 */  \t\tINTEGER VigilElapsedTime, ";
  protected final String TEXT_137 = "\");" + NL + "fw_";
  protected final String TEXT_138 = ".write(\"/* 62 */  \t\tINTEGER VigilWaitTime, ";
  protected final String TEXT_139 = "\");" + NL + "fw_";
  protected final String TEXT_140 = ".write(\"/* 63 */  \t\tINTEGER VolumeCount, ";
  protected final String TEXT_141 = "\");" + NL + "fw_";
  protected final String TEXT_142 = ".write(\"/* 64 */  \t\tVARCHAR AccessModuleName, ";
  protected final String TEXT_143 = "\");" + NL + "fw_";
  protected final String TEXT_144 = ".write(\"/* 65 */  \t\tVARCHAR AccessModuleInitStr, ";
  protected final String TEXT_145 = "\");" + NL + "fw_";
  protected final String TEXT_146 = ".write(\"/* 66 */  \t\tVARCHAR DirectoryPath, ";
  protected final String TEXT_147 = "\");" + NL + "fw_";
  protected final String TEXT_148 = ".write(\"/* 67 */  \t\tVARCHAR ExpirationDate, ";
  protected final String TEXT_149 = "\");" + NL + "fw_";
  protected final String TEXT_150 = ".write(\"/* 68 */  \t\tVARCHAR IndicatorMode, ";
  protected final String TEXT_151 = "\");" + NL + "fw_";
  protected final String TEXT_152 = ".write(\"/* 69 */  \t\tVARCHAR PrimarySpace, ";
  protected final String TEXT_153 = "\");" + NL + "fw_";
  protected final String TEXT_154 = ".write(\"/* 70 */  \t\tVARCHAR PrivateLogName, ";
  protected final String TEXT_155 = "\");" + NL + "fw_";
  protected final String TEXT_156 = ".write(\"/* 71 */  \t\tVARCHAR RecordFormat, ";
  protected final String TEXT_157 = "\");" + NL + "fw_";
  protected final String TEXT_158 = ".write(\"/* 72 */  \t\tVARCHAR RecordLength, ";
  protected final String TEXT_159 = "\");" + NL + "fw_";
  protected final String TEXT_160 = ".write(\"/* 73 */  \t\tVARCHAR SpaceUnit, ";
  protected final String TEXT_161 = "\");" + NL + "fw_";
  protected final String TEXT_162 = ".write(\"/* 74 */  \t\tVARCHAR TextDelimiter, ";
  protected final String TEXT_163 = "\");" + NL + "fw_";
  protected final String TEXT_164 = ".write(\"/* 75 */  \t\tVARCHAR VigilNoticeFileName, ";
  protected final String TEXT_165 = "\");" + NL + "fw_";
  protected final String TEXT_166 = ".write(\"/* 76 */  \t\tVARCHAR VigilStartTime, ";
  protected final String TEXT_167 = "\");" + NL + "fw_";
  protected final String TEXT_168 = ".write(\"/* 77 */  \t\tVARCHAR VigilStopTime, ";
  protected final String TEXT_169 = "\");" + NL + "fw_";
  protected final String TEXT_170 = ".write(\"/* 78 */  \t\tVARCHAR VolSerNumber, ";
  protected final String TEXT_171 = "\");" + NL + "fw_";
  protected final String TEXT_172 = ".write(\"/* 79 */  \t\tVARCHAR UnitType";
  protected final String TEXT_173 = "\");" + NL + "fw_";
  protected final String TEXT_174 = ".write(\"/* 80 */  \t);";
  protected final String TEXT_175 = "\");" + NL + "fw_";
  protected final String TEXT_176 = ".write(\"/* 81 */  ";
  protected final String TEXT_177 = "\");" + NL + "fw_";
  protected final String TEXT_178 = ".write(\"/* 82 */  \tAPPLY";
  protected final String TEXT_179 = "\");" + NL + "fw_";
  protected final String TEXT_180 = ".write(\"/* 83 */  \t\t(";
  protected final String TEXT_181 = "\");" + NL;
  protected final String TEXT_182 = NL + "fw_";
  protected final String TEXT_183 = ".write(\"'INSERT INTO \"+ ";
  protected final String TEXT_184 = " + \".\" + ";
  protected final String TEXT_185 = "+\" (";
  protected final String TEXT_186 = ") VALUES (";
  protected final String TEXT_187 = ");'";
  protected final String TEXT_188 = "\");" + NL + "" + NL + "" + NL + "" + NL + "" + NL + "fw_";
  protected final String TEXT_189 = ".write(\"/* 85 */  \t\t)";
  protected final String TEXT_190 = "\");" + NL + "fw_";
  protected final String TEXT_191 = ".write(\"/* 86 */  \tTO OPERATOR";
  protected final String TEXT_192 = "\");" + NL + "fw_";
  protected final String TEXT_193 = ".write(\"/* 87 */  \t(";
  protected final String TEXT_194 = "\");" + NL + "fw_";
  protected final String TEXT_195 = ".write(\"/* 88 */  \t\t\" + ";
  protected final String TEXT_196 = " + \"[1]";
  protected final String TEXT_197 = "\");" + NL + "fw_";
  protected final String TEXT_198 = ".write(\"/* 89 */  ";
  protected final String TEXT_199 = "\");" + NL + "fw_";
  protected final String TEXT_200 = ".write(\"/* 90 */  \t\tATTRIBUTES";
  protected final String TEXT_201 = "\");" + NL + "fw_";
  protected final String TEXT_202 = ".write(\"/* 91 */  \t\t(";
  protected final String TEXT_203 = "\");" + NL + "fw_";
  protected final String TEXT_204 = ".write(\"/* 92 */  \t\t\tUserName = '\" + ";
  protected final String TEXT_205 = " + \"', ";
  protected final String TEXT_206 = "\");";
  protected final String TEXT_207 = " " + NL + "\tfinal String decryptedPassword_";
  protected final String TEXT_208 = " = routines.system.PasswordEncryptUtil.decryptPassword(";
  protected final String TEXT_209 = ");";
  protected final String TEXT_210 = NL + "\tfinal String decryptedPassword_";
  protected final String TEXT_211 = " = ";
  protected final String TEXT_212 = "; ";
  protected final String TEXT_213 = NL + "fw_";
  protected final String TEXT_214 = ".write(\"/* 93 */  \t\t\tUserPassword = '\" + decryptedPassword_";
  protected final String TEXT_215 = " + \"', ";
  protected final String TEXT_216 = "\");" + NL + "fw_";
  protected final String TEXT_217 = ".write(\"/* 94 */  \t\t\tLogTable = '\" + tableFullName_";
  protected final String TEXT_218 = " + \"_log',";
  protected final String TEXT_219 = "\"); " + NL + "fw_";
  protected final String TEXT_220 = ".write(\"/* 95 */  \t\t\tTargetTable = '\" + tableFullName_";
  protected final String TEXT_221 = " + \"', ";
  protected final String TEXT_222 = "\");" + NL + "fw_";
  protected final String TEXT_223 = ".write(\"/* 96 */  \t\t\tTdpId = '\" + ";
  protected final String TEXT_224 = " + \"'";
  protected final String TEXT_225 = "\");" + NL + "fw_";
  protected final String TEXT_226 = ".write(\"/* 97 */  \t\t)";
  protected final String TEXT_227 = "\");" + NL + "fw_";
  protected final String TEXT_228 = ".write(\"/* 98 */  \t)";
  protected final String TEXT_229 = "\");" + NL + "fw_";
  protected final String TEXT_230 = ".write(\"/* 99 */  \tSELECT * FROM OPERATOR";
  protected final String TEXT_231 = "\");" + NL + "fw_";
  protected final String TEXT_232 = ".write(\"/* 100 */  \t(";
  protected final String TEXT_233 = "\");" + NL + "fw_";
  protected final String TEXT_234 = ".write(\"/* 101 */  \t\t\" + ";
  protected final String TEXT_235 = " + \"[1]";
  protected final String TEXT_236 = "\");" + NL + "fw_";
  protected final String TEXT_237 = ".write(\"/* 102 */  ";
  protected final String TEXT_238 = "\");" + NL + "fw_";
  protected final String TEXT_239 = ".write(\"/* 103 */  \t\tATTRIBUTES";
  protected final String TEXT_240 = "\");" + NL + "fw_";
  protected final String TEXT_241 = ".write(\"/* 104 */  \t\t(";
  protected final String TEXT_242 = "\");" + NL + "fw_";
  protected final String TEXT_243 = ".write(\"/* 105 */  \t\t\tFileName = '\" + ";
  protected final String TEXT_244 = " + \"', ";
  protected final String TEXT_245 = "\");" + NL + "fw_";
  protected final String TEXT_246 = ".write(\"/* 106 */  \t\t\tFormat = 'DELIMITED', ";
  protected final String TEXT_247 = "\");" + NL + "fw_";
  protected final String TEXT_248 = ".write(\"/* 107 */  \t\t\tOpenMode = 'Read', ";
  protected final String TEXT_249 = "\");" + NL + "fw_";
  protected final String TEXT_250 = ".write(\"/* 108 */  \t\t\tDirectoryPath = '', ";
  protected final String TEXT_251 = "\");" + NL + "fw_";
  protected final String TEXT_252 = ".write(\"/* 109 */  \t\t\tIndicatorMode = 'N', ";
  protected final String TEXT_253 = "\");" + NL + "fw_";
  protected final String TEXT_254 = ".write(\"/* 110 */  \t\t\tTextDelimiter = '\" + ";
  protected final String TEXT_255 = " + \"'";
  protected final String TEXT_256 = "\");" + NL + "fw_";
  protected final String TEXT_257 = ".write(\"/* 111 */  \t\t)";
  protected final String TEXT_258 = "\");" + NL + "fw_";
  protected final String TEXT_259 = ".write(\"/* 112 */  \t);";
  protected final String TEXT_260 = "\");" + NL + "fw_";
  protected final String TEXT_261 = ".write(\"/* 113 */  );";
  protected final String TEXT_262 = "\");" + NL;
  protected final String TEXT_263 = NL + "fw_";
  protected final String TEXT_264 = ".close();" + NL;
  protected final String TEXT_265 = NL + "\t\t\tString[] sb_";
  protected final String TEXT_266 = "= {\"cmd\",\"/c\",\"tbuild -f \"+";
  protected final String TEXT_267 = "+\" \\\"\"+";
  protected final String TEXT_268 = "+";
  protected final String TEXT_269 = "+\".script\\\" > \\\"\"+";
  protected final String TEXT_270 = "+\"\\\" 2>&1\"};" + NL + "\t\t";
  protected final String TEXT_271 = NL + "\t\t\tString[] sb_";
  protected final String TEXT_272 = "= {\"sh\",\"-c\",\"tbuild -f \"+";
  protected final String TEXT_273 = "+\" \\\"\"+";
  protected final String TEXT_274 = "+";
  protected final String TEXT_275 = "+\".scr\\\" > \\\"\"+";
  protected final String TEXT_276 = "+\"\\\" 2>&1\"};" + NL + "\t\t";
  protected final String TEXT_277 = NL + "\t\tString[] sb_";
  protected final String TEXT_278 = "= {\"cmd\",\"/c\",\"tbuild -f \\\"\"+";
  protected final String TEXT_279 = "+";
  protected final String TEXT_280 = "+\".script\\\" > \\\"\"+";
  protected final String TEXT_281 = "+\"\\\" 2>&1\"};" + NL + "\t";
  protected final String TEXT_282 = NL + "\t\tString[] sb_";
  protected final String TEXT_283 = "= {\"sh\",\"-c\",\"tbuild -f \\\"\"+";
  protected final String TEXT_284 = "+";
  protected final String TEXT_285 = "+\".scr\\\" > \\\"\"+";
  protected final String TEXT_286 = "+\"\\\" 2>&1\"};" + NL + "\t";
  protected final String TEXT_287 = NL + "final Process process_";
  protected final String TEXT_288 = " = Runtime.getRuntime().exec(sb_";
  protected final String TEXT_289 = "); " + NL + "Thread normal_";
  protected final String TEXT_290 = " = new Thread() {" + NL + "    public void run() {" + NL + "    \ttry {" + NL + "    \t\tjava.io.BufferedReader reader = new java.io.BufferedReader(new java.io.InputStreamReader(process_";
  protected final String TEXT_291 = ".getInputStream()));" + NL + "    \t\tString line = \"\";" + NL + "    \t\ttry {" + NL + "    \t\t\twhile((line = reader.readLine()) != null) {" + NL + "    \t\t\t   System.out.println(line);" + NL + "    \t        }" + NL + "    \t    } finally {" + NL + "    \t         reader.close();" + NL + "    \t    }" + NL + "        }catch(java.io.IOException ioe) {" + NL + "    \t\tioe.printStackTrace();" + NL + "    \t}" + NL + "    }" + NL + "};" + NL + "normal_";
  protected final String TEXT_292 = ".start();" + NL + "" + NL + "Thread error_";
  protected final String TEXT_293 = " = new Thread() {" + NL + "\tpublic void run() {" + NL + "\t\ttry {" + NL + "\t\t\tjava.io.BufferedReader reader = new java.io.BufferedReader(new java.io.InputStreamReader(process_";
  protected final String TEXT_294 = ".getErrorStream()));" + NL + "\t\t\tString line = \"\";" + NL + "\t\t\ttry {" + NL + "\t\t\t\twhile((line = reader.readLine()) != null) {" + NL + "\t\t\t\t\tSystem.err.println(line);" + NL + "\t\t\t\t}" + NL + "\t\t\t} finally {" + NL + "\t\t\t\treader.close();" + NL + "\t\t\t}" + NL + "\t\t} catch(java.io.IOException ioe) {" + NL + "\t\t   ioe.printStackTrace();" + NL + "\t\t}" + NL + "\t}" + NL + "};" + NL + "error_";
  protected final String TEXT_295 = ".start();" + NL + "" + NL + "process_";
  protected final String TEXT_296 = ".waitFor();" + NL + "" + NL + "normal_";
  protected final String TEXT_297 = ".interrupt();" + NL + "" + NL + "error_";
  protected final String TEXT_298 = ".interrupt();" + NL + "" + NL + "globalMap.put(\"";
  protected final String TEXT_299 = "_EXIT_VALUE\", process_";
  protected final String TEXT_300 = ".exitValue());" + NL;
  protected final String TEXT_301 = NL + "\tif(process_";
  protected final String TEXT_302 = ".exitValue()>=";
  protected final String TEXT_303 = ") {" + NL + "\t\tthrow new RuntimeException(\"TPT returned exit code \"+process_";
  protected final String TEXT_304 = ".exitValue());" + NL + "\t}";
  protected final String TEXT_305 = NL + "}finally{" + NL + "\ttry{" + NL + "\t\tfile_";
  protected final String TEXT_306 = ".delete();" + NL + "\t}catch(Exception e_";
  protected final String TEXT_307 = "){" + NL + "\t" + NL + "\t}" + NL + "}";

  public String generate(Object argument)
  {
    final StringBuffer stringBuffer = new StringBuffer();
    
CodeGeneratorArgument codeGenArgument = (CodeGeneratorArgument) argument;
INode node = (INode)codeGenArgument.getArgument();
String cid = node.getUniqueName();

String tdpid= ElementParameterParser.getValue(node, "__TDPID__");
String jobName= ElementParameterParser.getValue(node, "__JOB_NAME__");
String operatorLoad= ElementParameterParser.getValue(node, "__OPERATOR_LOAD__");
String operatorDataConnector= ElementParameterParser.getValue(node, "__OPERATOR_DATA_CONNECTOR__");
String layoutName= ElementParameterParser.getValue(node, "__LAYOUT_NAME__");
String dbname= ElementParameterParser.getValue(node, "__DBNAME__");
String dbuser= ElementParameterParser.getValue(node, "__USER__");

String table= ElementParameterParser.getValue(node, "__TABLE__");

String scriptPath= ElementParameterParser.getValue(node, "__SCRIPT_PATH__");
String execution= ElementParameterParser.getValue(node, "__EXECUTION__");
String loadFile= ElementParameterParser.getValue(node, "__LOAD_FILE__");
String separator= ElementParameterParser.getValue(node, "__FIELD_SEPARATOR__");
String errorFile= ElementParameterParser.getValue(node, "__ERROR_FILE__");
String beginLoad= ElementParameterParser.getValue(node, "__BEGINLOAD_ADVANCEDPARAM__");
boolean returnCodeDie= ElementParameterParser.getValue(node, "__RETURN_CODE_DIE__").equals("true");
String returnCode= ElementParameterParser.getValue(node, "__RETURN_CODE__");
boolean specifyLogTable= ElementParameterParser.getValue(node, "__SPECIFY_LOG_TABLE__").equals("true");
String logTable= ElementParameterParser.getValue(node, "__LOG_TABLE_TABLE__");

String defineCharset = ElementParameterParser.getValue(node, "__DEFINE_CHARSET__");
String charset = ElementParameterParser.getValue(node, "__CHARSET__");

//windows line separator as default
String lineSeparator = "\\r\\n";
if("Unix".equals(execution)){
	lineSeparator = "\\n";
}
if(!scriptPath.endsWith("/\"")){
	scriptPath = scriptPath+	"+\"/\"";
}
if(loadFile.indexOf("/") !=0 && ("Windows").equals(execution)){
	loadFile = loadFile.replaceAll("/", "\\\\\\\\");
}

String dbmsId = "teradata_id";

List<IMetadataColumn> columnList = null;
List<IMetadataTable> metadatas = node.getMetadataList();
if ((metadatas!=null)&&(metadatas.size()>0)) {
	IMetadataTable metadata = metadatas.get(0);
	if (metadata!=null) {
		columnList = metadata.getListColumns();
	}
}

    stringBuffer.append(TEXT_1);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_2);
    stringBuffer.append(dbname);
    stringBuffer.append(TEXT_3);
    stringBuffer.append(table);
    stringBuffer.append(TEXT_4);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_5);
    stringBuffer.append(scriptPath);
    stringBuffer.append(TEXT_6);
    stringBuffer.append(table);
    stringBuffer.append(TEXT_7);
    if("Windows".equals(execution)){
    stringBuffer.append(TEXT_8);
    }else{
    stringBuffer.append(TEXT_9);
    }
    stringBuffer.append(TEXT_10);
    //build script---------------------------------------------------------
    stringBuffer.append(TEXT_11);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_12);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_13);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_14);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_15);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_16);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_17);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_18);
    stringBuffer.append(jobName);
    stringBuffer.append(TEXT_19);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_20);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_21);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_22);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_23);
    stringBuffer.append(operatorLoad);
    stringBuffer.append(TEXT_24);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_25);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_26);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_27);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_28);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_29);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_30);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_31);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_32);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_33);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_34);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_35);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_36);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_37);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_38);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_39);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_40);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_41);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_42);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_43);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_44);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_45);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_46);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_47);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_48);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_49);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_50);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_51);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_52);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_53);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_54);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_55);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_56);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_57);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_58);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_59);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_60);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_61);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_62);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_63);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_64);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_65);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_66);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_67);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_68);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_69);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_70);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_71);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_72);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_73);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_74);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_75);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_76);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_77);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_78);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_79);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_80);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_81);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_82);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_83);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_84);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_85);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_86);
    stringBuffer.append(layoutName);
    stringBuffer.append(TEXT_87);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_88);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_89);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_90);
    
if(columnList!=null){
	int counter = 1;
	for(IMetadataColumn column:columnList){	
		if( columnList.size() != counter){	
    stringBuffer.append(TEXT_91);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_92);
    stringBuffer.append(column.getOriginalDbColumnName());
    stringBuffer.append(TEXT_93);
    stringBuffer.append(column.getLength() == null ? 0 : column.getLength());
    stringBuffer.append(TEXT_94);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_95);
    
		} else {
	
    stringBuffer.append(TEXT_96);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_97);
    stringBuffer.append(column.getOriginalDbColumnName());
    stringBuffer.append(TEXT_98);
    stringBuffer.append(column.getLength() == null ? 0 : column.getLength());
    stringBuffer.append(TEXT_99);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_100);
     	}
		counter++;
	}
}

    stringBuffer.append(TEXT_101);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_102);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_103);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_104);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_105);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_106);
    stringBuffer.append(operatorDataConnector);
    stringBuffer.append(TEXT_107);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_108);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_109);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_110);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_111);
    stringBuffer.append(layoutName);
    stringBuffer.append(TEXT_112);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_113);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_114);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_115);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_116);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_117);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_118);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_119);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_120);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_121);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_122);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_123);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_124);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_125);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_126);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_127);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_128);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_129);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_130);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_131);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_132);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_133);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_134);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_135);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_136);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_137);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_138);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_139);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_140);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_141);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_142);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_143);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_144);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_145);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_146);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_147);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_148);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_149);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_150);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_151);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_152);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_153);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_154);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_155);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_156);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_157);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_158);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_159);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_160);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_161);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_162);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_163);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_164);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_165);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_166);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_167);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_168);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_169);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_170);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_171);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_172);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_173);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_174);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_175);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_176);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_177);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_178);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_179);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_180);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_181);
    
StringBuilder insertColSQL = new StringBuilder();
StringBuilder insertValueSQL = new StringBuilder();
if(columnList!=null){
	String columnName = "";
 	for(IMetadataColumn column:columnList){	
 		columnName= column.getOriginalDbColumnName();
 		if(insertColSQL.length()>0){
 			insertColSQL.append(",");
 		}
 		insertColSQL.append(columnName);
 		
 		if(insertValueSQL.length()>0){
 			insertValueSQL.append(",");
 		}
 		insertValueSQL.append(":").append(columnName);
	}
}

    stringBuffer.append(TEXT_182);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_183);
    stringBuffer.append(dbname);
    stringBuffer.append(TEXT_184);
    stringBuffer.append(table);
    stringBuffer.append(TEXT_185);
    stringBuffer.append(insertColSQL.toString());
    stringBuffer.append(TEXT_186);
    stringBuffer.append(insertValueSQL.toString());
    stringBuffer.append(TEXT_187);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_188);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_189);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_190);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_191);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_192);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_193);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_194);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_195);
    stringBuffer.append(operatorLoad);
    stringBuffer.append(TEXT_196);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_197);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_198);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_199);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_200);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_201);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_202);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_203);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_204);
    stringBuffer.append(dbuser);
    stringBuffer.append(TEXT_205);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_206);
    
String passwordFieldName = "__PASS__";

    if (ElementParameterParser.canEncrypt(node, passwordFieldName)) {
    stringBuffer.append(TEXT_207);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_208);
    stringBuffer.append(ElementParameterParser.getEncryptedValue(node, passwordFieldName));
    stringBuffer.append(TEXT_209);
    } else {
    stringBuffer.append(TEXT_210);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_211);
    stringBuffer.append( ElementParameterParser.getValue(node, passwordFieldName));
    stringBuffer.append(TEXT_212);
    }
    stringBuffer.append(TEXT_213);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_214);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_215);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_216);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_217);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_218);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_219);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_220);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_221);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_222);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_223);
    stringBuffer.append(tdpid);
    stringBuffer.append(TEXT_224);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_225);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_226);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_227);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_228);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_229);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_230);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_231);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_232);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_233);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_234);
    stringBuffer.append(operatorDataConnector);
    stringBuffer.append(TEXT_235);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_236);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_237);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_238);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_239);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_240);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_241);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_242);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_243);
    stringBuffer.append(loadFile);
    stringBuffer.append(TEXT_244);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_245);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_246);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_247);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_248);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_249);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_250);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_251);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_252);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_253);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_254);
    stringBuffer.append(separator);
    stringBuffer.append(TEXT_255);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_256);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_257);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_258);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_259);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_260);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_261);
    stringBuffer.append(lineSeparator);
    stringBuffer.append(TEXT_262);
    //write script to file-------------------------------------------------
    stringBuffer.append(TEXT_263);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_264);
    //run tbuild (TPT) command----------------------------------------------------
    if("true".equals(defineCharset)) {
	if(!("".equals(charset))) {
		if("Windows".equals(execution)){
    stringBuffer.append(TEXT_265);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_266);
    stringBuffer.append(charset);
    stringBuffer.append(TEXT_267);
    stringBuffer.append(scriptPath);
    stringBuffer.append(TEXT_268);
    stringBuffer.append(table);
    stringBuffer.append(TEXT_269);
    stringBuffer.append(errorFile);
    stringBuffer.append(TEXT_270);
    }else{
    stringBuffer.append(TEXT_271);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_272);
    stringBuffer.append(charset);
    stringBuffer.append(TEXT_273);
    stringBuffer.append(scriptPath);
    stringBuffer.append(TEXT_274);
    stringBuffer.append(table);
    stringBuffer.append(TEXT_275);
    stringBuffer.append(errorFile);
    stringBuffer.append(TEXT_276);
    }
	}
} else {
	if("Windows".equals(execution)){
    stringBuffer.append(TEXT_277);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_278);
    stringBuffer.append(scriptPath);
    stringBuffer.append(TEXT_279);
    stringBuffer.append(table);
    stringBuffer.append(TEXT_280);
    stringBuffer.append(errorFile);
    stringBuffer.append(TEXT_281);
    }else{
    stringBuffer.append(TEXT_282);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_283);
    stringBuffer.append(scriptPath);
    stringBuffer.append(TEXT_284);
    stringBuffer.append(table);
    stringBuffer.append(TEXT_285);
    stringBuffer.append(errorFile);
    stringBuffer.append(TEXT_286);
    }
}
    stringBuffer.append(TEXT_287);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_288);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_289);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_290);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_291);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_292);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_293);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_294);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_295);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_296);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_297);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_298);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_299);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_300);
    
if(returnCodeDie) {

    stringBuffer.append(TEXT_301);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_302);
    stringBuffer.append(returnCode);
    stringBuffer.append(TEXT_303);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_304);
    	
}

    stringBuffer.append(TEXT_305);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_306);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_307);
    return stringBuffer.toString();
  }
}
